[mypy]
exclude = (?x)(
    pyodide_main\.py$     # ignore pyodide stuff
    | ^setup\.py$         # ignore wheel stuff
    | pandas_tutor/tests  # ignore test cases
  )
warn_unused_configs = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-seaborn.*]
ignore_missing_imports = True

[mypy-docopt.*]
ignore_missing_imports = True

[mypy-pympler.*]
ignore_missing_imports = True

[mypy-prettyprinter.*]
ignore_missing_imports = True
